In [4]:
                          **** NUMPY LIBRARY - RAJESH BOYA ****


In [6]:
#IMPORT NUMPY
import numpy as np

#CREATING A ARRAY
a=np.array([1,2])
print("1-DIMENTIONAL ARRAY : \n",a)

1-DIMENTIONAL ARRAY : 
 [1 2]


In [28]:
b=np.array([[1,5,5,8,5,5,1,7],[9,4,3,4,6,7,1,2]])
print("2-DIMENTIONAL ARRAY : \n",b)

2-DIMENTIONAL ARRAY : 
 [[1 5 5 8 5 5 1 7]
 [9 4 3 4 6 7 1 2]]


In [12]:
c=np.array([[[7,7],[8,9],[9,8]]])
print("3-DIMENTIONAL ARRAY : \n",c)

3-DIMENTIONAL ARRAY : 
 [[[7 7]
  [8 9]
  [9 8]]]


In [14]:
#DIMENSIONS
b.ndim
b

array([[1, 5],
       [1, 2],
       [2, 3],
       [2, 6]])

In [16]:
print("NUMBER OF ROWS AND COLUMNS :",b.shape)

NUMBER OF ROWS AND COLUMNS : (4, 2)


In [18]:
#DataType
print("DATA TYPE : ",b.dtype)

DATA TYPE :  int32


In [20]:
print("SIZE OF EACH ELEMENT : ",b.itemsize)

SIZE OF EACH ELEMENT :  4


In [22]:
#1 element=4bytes
print("SIZE OF TOTAL ARRAY IN BYTES : ",b.nbytes)

SIZE OF TOTAL ARRAY IN BYTES :  32


In [32]:
# ACCESSING ELEMENTS 

print("ACCESSING A PARTICULAR ELEMENT : ",b[1,4])
print("ACCESSING A SPECIFIC ROW : ",b[1,:])
print("ACCESSING A SPECIFIC COLUMN : ",b[:,4])

ACCESSING A PARTICULAR ELEMENT :  6
ACCESSING A SPECIFIC ROW :  [9 4 3 4 6 7 1 2]
ACCESSING A SPECIFIC COLUMN :  [5 6]


In [40]:
#CREATING ARRAYS
# SYNTAX : [ NO. OF ARRAYS , NO.OF ROWS, NO.OF COLUMNS ]

print("ARRAY OF ZEROS : \n",np.zeros((2,5,4)))

ARRAY OF ZEROS : 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [44]:
print("ARRAY OF ONES : \n",np.ones((5,7)))

ARRAY OF ONES : 
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [46]:
print("ARRAY OF SPECIFIC NUMBER : \n",np.full((1,3,3),69))

ARRAY OF SPECIFIC NUMBER : 
 [[[69 69 69]
  [69 69 69]
  [69 69 69]]]


In [52]:
print("ARRAY OF RANDOM NUMBERS : \n",np.random.rand(3,3))

ARRAY OF RANDOM NUMBERS : 
 [[0.38404017 0.06598908 0.47751645]
 [0.64874017 0.59799865 0.29461554]
 [0.21598717 0.40874269 0.82264028]]


In [54]:
print("IDENTITY MATRIX : \n",np.identity(7))

IDENTITY MATRIX : 
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
